

# Configuração de build padrão
[build]
command = "npm run build"   # Comando de build da aplicação
publish = "dist"            # Pasta onde os arquivos finais são gerados

[build.environment]
  NODE_VERSION = "18"




# Configuração do ambiente de desenvolvimento local (Netlify Dev)
[dev]
command = "npm run dev"     # Comando que inicia o servidor de desenvolvimento (Vite)
port = 8888                 # Porta onde o Netlify Dev escuta (diferente da porta do Vite)
targetPort = 5173           # Porta real onde o Vite roda por padrão
publish = "dist"           # Pasta pública usada no dev também

# Headers para permitir o Visual Editor
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers específicos para o Stackbit/Visual Editor
[[headers]]
  for = "/_stackbit/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"

# Redirecionamentos para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200