[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/opt/buildhome/.nvm/versions/node/v18.20.4"

[[plugins]]
  package = "@netlify/plugin-stackbit"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"
  autoLaunch = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_stackbit/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"